apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: loyality-net
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.15.0
          args: ["-e", "-E", 'output.logstash.hosts=["logstash:5044"]']
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
