apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: loyality-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch:9200"
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              value: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlOmxlRnF3ZmZHU18tMGJTNnNMV0FUN3c"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
            - name: SERVER_HOST
              value: "0.0.0.0" # Allows external access
            - name: SERVER_PUBLICBASEURL
              value: "http://172.20.150.17:30097" # Your Fedora IP with NodePort
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: loyality-net
spec:
  type: NodePort # Explicitly set to NodePort for external access
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30097 # Fixed node port for consistency
