apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: loyality-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch:9200"
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              value: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlOmxlRnF3ZmZHU18tMGJTNnNMV0FUN3c"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: loyality-net
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
