apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: loyality-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: loyality-net
spec:
  type: LoadBalancer # Use LoadBalancer if on cloud, NodePort for local cluster
  selector:
    app: nginx
  ports:
    - port: 80 # Cluster IP port
      targetPort: 80 # Container port
      nodePort: 30080 # Node port to access externally (only for NodePort type)
