apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: loyality-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.0
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: loyality-net
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => ["https://elasticsearch:9200"]
        user => "elastic"
        password => "ZqYCrBsYu3kejHaaXYe1"
        ssl => true
        ssl_certificate_verification => false
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: loyality-net
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
