# ------------------------
# Persistent Volume Claim for Postgres
# ------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: loyality-net
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ------------------------
# Postgres Deployment
# ------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: loyality-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keycloakdb
            - name: POSTGRES_USER
              value: loyalityuser
            - name: POSTGRES_PASSWORD
              value: loyalitypass
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "loyalityuser"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# ------------------------
# Postgres Service
# ------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: loyality-net
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
